# Generated by Django 5.1.2 on 2024-10-27 22:26

import Posts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=350)),
                ('created', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=350)),
                ('PostFile', models.FileField(upload_to=Posts.models.getUploadFileUrl, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["['jpeg', 'jpg', 'png', 'mp3', 'mp4']"])])),
                ('preview', models.ImageField(upload_to=Posts.models.getUploadFileUrl)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
