# Generated by Django 5.1.2 on 2024-10-27 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='preview',
        ),
    ]
