# Generated by Django 5.0.7 on 2024-10-30 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0004_alter_posts_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='author',
            new_name='owner',
        ),
    ]
