# Generated by Django 5.1.2 on 2024-11-11 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Likes', '0002_alter_likes_owner'),
        ('Posts', '0006_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='Posts.posts'),
        ),
    ]
